# Generated by Django 4.2.1 on 2023-05-25 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='customer id')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('mobile_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('term_days', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Project_Constructions',
            fields=[
                ('construction_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='construction id')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, default=99999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project_Constructions',
                'db_table': 'Project_Constructions',
            },
        ),
        migrations.CreateModel(
            name='Project_Status',
            fields=[
                ('status_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='status id')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, default=99999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project_Status',
                'db_table': 'Project_Status',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='project id')),
                ('project_name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modules_w', models.IntegerField(blank=True, null=True)),
                ('eur_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subcontracting', models.CharField(blank=True, max_length=150, null=True)),
                ('comment', models.CharField(blank=True, max_length=350, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('construction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project_constructions')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.customers')),
                ('status_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project_status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Project_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, default='', null=True)),
                ('end_date', models.DateField(blank=True, default='', null=True)),
                ('work_time', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('break_time', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('neto_time', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('isDone', models.CharField(default='ne', editable=False, max_length=5)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.projects')),
                ('user', models.ForeignKey(blank=True, default=99999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project_jobs',
                'db_table': 'Project_jobs',
            },
        ),
        migrations.CreateModel(
            name='Project_Expenditures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project_Expenditures',
                'db_table': 'Project_Expenditures',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_no', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='invoice number')),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, default=None, null=True)),
                ('term_days', models.IntegerField(default=0)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='Neapmokėta', editable=False, max_length=20)),
                ('total_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'db_table': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Invoice_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='Projects.invoices')),
                ('user', models.ForeignKey(blank=True, default=99999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoice_payments',
                'db_table': 'Invoice_payments',
            },
        ),
        migrations.AddConstraint(
            model_name='project_status',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_status'),
        ),
        migrations.AddConstraint(
            model_name='project_constructions',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_construction'),
        ),
    ]
