# Generated by Django 4.2.1 on 2023-05-06 15:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('mobile_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('term_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('construction_type', models.CharField(choices=[('Ploksčias bituminis', 'Ploksčias bituminis'), ('Antžeminė', 'Antžeminė'), ('Classic valcuota skarda', 'Classic valcuota skarda'), ('Trapecinė skarda', 'Trapecinė skarda'), ('Čerpinė skarda', 'Čerpinė skarda'), ('Šiferis', 'Šiferis'), ('Molinė čerpė', 'Molinė čerpė'), ('Šlaitinė', 'Šlaitinė'), ('Betoninė čerpė', 'Betoninė čerpė'), ('Bituminė čerpė', 'Bituminė čerpė')], default='', max_length=100)),
                ('kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eur_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modules_w', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Gautas kontaktas iš Saulės grąžos', 'Gautas kontaktas iš Saulės grąžos'), ('LDA kontraktas', 'LDA kontraktas'), ('Susisiekta', 'Susisiekta'), ('Aplankyta', 'Aplankyta'), ('Išsiųstas pasiūlymas', 'Išsiųstas pasiūlymas'), ('Pasiektas susitarimas', 'Pasiektas susitarimas'), ('Pasirašyta sutartis', 'Pasirašyta sutartis'), ('Projektas įgyvendintas', 'Projektas įgyvendintas'), ('Rangovo deklaracija', 'Rangovo deklaracija'), ('Perduota subrangai', 'Perduota subrangai')], default='', max_length=100)),
                ('subcontracting', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=350, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Projects.clients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Project_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, default='', null=True)),
                ('end_date', models.DateField(blank=True, default='', null=True)),
                ('done', models.BooleanField(default=False)),
                ('time', models.DurationField(blank=True, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Projects.projects')),
            ],
            options={
                'db_table': 'Project_jobs',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('deadline_date', models.DateField(blank=True, default='', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=20)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Projects.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Invoice_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, default='', null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Projects.invoices')),
            ],
            options={
                'db_table': 'Invoice_payments',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
