# Generated by Django 4.2.1 on 2023-05-06 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='invoice_payments',
            options={'verbose_name_plural': 'Invoice_payments'},
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='project_jobs',
            options={'verbose_name_plural': 'Project_jobs'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='projects',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projects',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
