# Generated by Django 4.2.1 on 2023-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_invoices_total_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_payments',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
