# Generated by Django 4.2.1 on 2023-05-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_alter_invoices_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='status',
        ),
    ]
