# Generated by Django 4.2.1 on 2023-05-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_remove_invoices_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
