# Generated by Django 4.2.1 on 2023-05-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_invoices_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(default='Neapmokėta', max_length=20),
        ),
    ]
