# Generated by Django 4.2.1 on 2023-05-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_alter_invoices_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_jobs',
            name='time',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='construction_type',
            field=models.CharField(choices=[('Ploksčias bituminis', 'Ploksčias bituminis'), ('Antžeminė', 'Antžeminė'), ('Classic valcuota skarda', 'Classic valcuota skarda'), ('Trapecinė skarda', 'Trapecinė skarda'), ('Čerpinė skarda', 'Čerpinė skarda'), ('Šiferis', 'Šiferis'), ('Molinė čerpė', 'Molinė čerpė'), ('Šlaitinė', 'Šlaitinė'), ('Betoninė čerpė', 'Betoninė čerpė'), ('Bituminė čerpė', 'Bituminė čerpė')], default='', max_length=100),
        ),
    ]
