# Generated by Django 4.2.1 on 2023-05-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_alter_project_jobs_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_jobs',
            name='time',
            field=models.DurationField(blank=True, default='00:00:00', null=True),
        ),
    ]
