# Generated by Django 4.2.1 on 2023-05-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_alter_projects_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
