# Generated by Django 4.2.1 on 2023-05-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0011_alter_projects_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_payments',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments', to='Projects.invoices'),
        ),
    ]
