# Generated by Django 4.2.1 on 2023-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_alter_invoice_payments_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(default='Neapmokėta', editable=False, max_length=20),
        ),
    ]
